default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: seedling_development

test:
  <<: *default
  database: seedling_test

production:
  <<: *default
  database: seedling_production
  username: seedling
  password: <%= ENV['FORAGE_DATABASE_PASSWORD'] %>
